// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QOQOPOOOVOPO'#C_OOOO'#C^'#C^QQOPOOO[OPO,58yOOOO,58x,58xOOOO'#Ca'#CaOOOO1G.e1G.e",
  stateData: "d~OSPO~OWSO~OSUOUUO~O",
  goto: "cUPPVYP`RROQQORTRRVS",
  nodeNames: "⚠ Program StatementList Statement Identifier Expression Number",
  maxTerm: 8,
  skippedNodes: [0],
  repeatNodeCount: 0,
  tokenData: "%Z~RQxyX!_!`%U~[P!}#O_~bQ!Q!Rh#T#U!]~kP}!On~qP!Z![t~wP#P#Qz~}P{|!Q~!TPyz!W~!]OU~~!`P}!O!c~!fP#n#o!i~!lP!c!d!o~!rP}!O!u~!xP!|!}!{~#OP#R#S#R~#UP#P#Q#X~#[P!}#O#_~#bP#T#U#e~#hP}!O#k~#nP#n#o#q~#tP!c!d#w~#zP}!O#}~$QP!|!}$T~$WP!Q!R$Z~$^P}!O$a~$dP!Z![$g~$jP#R#S$m~$pP#P#Q$s~$vPz{$y~$|Pyz%P~%UOS~~%ZOW~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
